### ISSUE TITLE
Pull-through cache for mcr.microsoft.com is not working

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/containerregistry#9]
_Copied from https://github.com/dotnet/dotnet-docker/issues/1434 by @dngcsc_

## Steps to reproduce the issue
1. Create a local docker registry that acts as pull-through cache for mcr.microsoft.com:

**docker-compose.yml**

```
version: '3'
services:
  mcr:
    image: registry:2.6.2
    ports:
     - "5003:5000"
    volumes:
     - ./registry/conf/mcr-mirror-config.yml:/etc/docker/registry/config.yml
```

**mcr-mirror-config.yml**
```
version: 0.1

# other fields omitted

proxy:
  remoteurl: https://mcr.microsoft.com
```
2. Change docker daemon to use `http://localhost:5003` as registry mirror
3. `docker pull mcr.microsoft.com/dotnet/core/sdk:3.0-alpine`

## Expected behavior

`sdk:3.0-alpine` is cached in `mcr` registry

## Actual behavior

`mcr` registry is empty

## Additional information (e.g. issue happens only occasionally)

_Copied from https://github.com/dotnet/dotnet-docker/issues/1434#issuecomment-549393663 by @mthalman_

It's not clear from the [pull through cache documentation](https://docs.docker.com/registry/recipes/mirror/) whether this is even intended to be supported for registries other than Docker Hub.  Regardless, this issue would be more appropriate for the MCR repo since it's a function of the registry functionality, not the .NET Docker images themselves.
